FIRESTATION_TO_FIRSTBUILDING_LATERAL = 35


# TEST

# RESIDENTIAL_TALL_Y = 40
# RESIDENTIAL_MIDDLE_Y = 30
# RESIDENTIAL_SMALL_Y = 20


# TEXTRON TOWERS y Values CM

TEXTRON_TALL_Y = 200
TEXTRON_MIDDLE_Y = 110
TEXTRON_SMALL_Y = 30


# Residential District y Values CM

RESIDENTIAL_TALL_Y = 145
RESIDENTIAL_MIDDLE_Y = 25
RESIDENTIAL_SMALL_Y = 30